# Generated by Django 4.0.6 on 2022-07-08 16:26

import ResumeParser.jsonfield
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeParser', '0002_profile_remove_application_user_application_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opening',
            name='description',
            field=models.TextField(blank=True, default='', max_length=70),
        ),
        migrations.AddField(
            model_name='opening',
            name='weighting',
            field=ResumeParser.jsonfield.JSONField(default='{"Work Experience": [".25", {"[0-9]+[+][ years of experience]gm": ["10_UT_25"]}], "Tools": [".30", {"[react]gm": ["1_UC_10"], "[django]gm": ["1_UC_10"], "[tailwind]gm": ["1_UC_10"]}]}'),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(help_text='Please Submit PDF or DOCX file format', upload_to='UploadedResumes', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx'])]),
        ),
    ]
