# Generated by Django 4.0.6 on 2022-07-08 16:48

import ResumeParser.jsonfield
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeParser', '0003_opening_description_opening_weighting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opening',
            name='weighting',
            field=ResumeParser.jsonfield.JSONField(default='{"Work Experience": 0.454, "Tools": 0.545}'),
        ),
    ]
