# Generated by Django 4.0.6 on 2022-07-08 16:58

import ResumeParser.jsonfield
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeParser', '0004_alter_opening_weighting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opening',
            name='weighting',
            field=ResumeParser.jsonfield.JSONField(default='{"Work Experience": [0.454, {"[0-9]+[+][ years of experience]gm": [1, "UT", 1.0]}], "Tools": [0.545, {"[react]gm": [1, "UC", 0.333], "[django]gm": [1, "UC", 0.333], "[tailwind]gm": [1, "UC", 0.333]}]}'),
        ),
    ]
